pipeline {
    agent {
        docker {
            image 'maven:3.9.9-eclipse-temurin-21'
            args '-v /var/lib/jenkins/.m2:/root/.m2'
        }
    }

    options {
        skipStagesAfterUnstable()
    }

    stages {
        stage('Build') {
            steps {
                echo '🔧 Building the project...'
                sh 'mvn -Dmaven.repo.local=/root/.m2 -B -DskipTests clean package'
            }
        }

        stage('Test') {
            steps {
                echo '🧪 Running tests...'
                sh 'mvn -Dmaven.repo.local=/root/.m2 test'
            }
            post {
                always {
                    echo '📄 Publishing test results...'
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }

        stage('Deliver') {
            steps {
                echo '🚀 Delivering the application...'
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
