pipeline {
    agent {
        docker {
            image 'maven:3.9.9-eclipse-temurin-21'
            args '-u root:root -v /var/lib/jenkins/.m2:/var/maven/.m2'
        }
    }

    environment {
        MAVEN_OPTS = '-Dmaven.repo.local=/var/maven/.m2'
    }

    options {
        skipStagesAfterUnstable()
    }

    stages {
        stage('Build') {
            steps {
                echo '🔧 Building the project...'
                sh 'mvn $MAVEN_OPTS -B -DskipTests clean package'
            }
        }

        stage('Test') {
            steps {
                echo '🧪 Running tests...'
                sh 'mvn $MAVEN_OPTS test'
            }
            post {
                always {
                    echo '📄 Publishing test results...'
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }

        stage('Deliver') {
            steps {
                echo '🚀 Delivering the application...'
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
